#!/usr/bin/env bash
#Writing good and bad luck while saying "Best School" 10 times
n=1
while [ $n -le 10 ];
do
        if [ $n -eq 4 ]; then
                echo "bad luck"
	elif [ $n -eq 8 ]
		echo "good luck"
	else
		echo "Best School"	
        fi
        n=$(( n+1 ))
done
