#!/usr/bin/env bash
#Giving info about school
FILE="school"
if [ $FILE = -e ]
then
        echo "school file exists"
else
        echo "school file does not exist" 
        fi
        if [ $FILE = -e ]
	then [ $FILE == -s ]
        if [ $FILE = -s ]
        then
                echo "school file is empty"
        else
                echo "school file is not empty"
        fi
        if [ $FILE = -f ]
                then
                        echo "school is regular file"
                fi
        fi
