#!/usr/bin/env bash
#Giving info about school
FILE="school"
if [ -e "$FILE" ]
then
        echo "school file exists"
        if [ -s "$FILE" ]
        then
                echo "school file is not empty"
        else
                echo "school file is empty"
        fi
        if [ "$FILE" = -f ]
                then
                        echo "school is a regular file"
        fi
else
                echo "school file does not exist"               
fi
