#!/usr/bin/env bash
#Update and Install haproxy web server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install haproxy -y

#config
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back
backend http_back
    mode http
    balance roundrobin
    server 5536-web-01 15.237.114.138:80 check
    server 5536-web-02 15.188.87.126:80 check
EOF

sudo service haproxy restart
